all: reverse reverse-pointers

reverse: reverse.c
	gcc -o reverse -ggdb3 -pedantic -std=gnu99 -Wall -Werror reverse.c
reverse-pointers: reverse-pointers.c
	gcc -o reverse-pointers -ggdb3 -pedantic -std=gnu99 -Wall -Werror reverse-pointers.c
